version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-9'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7.6-0'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
      - APACHE_HTTP_PORT_NUMBER=80
      - APACHE_HTTPS_PORT_NUMBER=443
      - PRESTASHOP_EXTERNAL_HTTP_PORT_NUMBER=80
      - PRESTASHOP_EXTERNAL_HTTPS_PORT_NUMBER=443
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
